extends: default

rules:
  line-length:
    max: 100
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  document-start:
    present: false
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  colons:
    max-spaces-before: 0
    max-spaces-after: 1