when:
  - event: [push, pull_request]

steps:
  - name: format-and-lint
    image: debian:bullseye-slim
    commands:
      - apt-get update -y
      - apt-get install -y build-essential make
      - make install
      - make format
      - make lint
      
      # Security checks
      - echo "Running security checks..."
      - |
        # Check for hardcoded credentials
        ! grep -r -i "password\|secret\|key" --exclude-dir=.git --exclude="*.enc" .
      - |
        # Check for private keys
        ! find . -type f -name "*.pem" -o -name "*.key"

  - name: check-nginx
    image: nginx:alpine
    commands:
      - echo "Validating nginx configuration..."
      - nginx -t -c /etc/nginx/nginx.conf