when:
  - event: [push, pull_request]

steps:
  - name: format-and-lint
    image: debian:bullseye-slim
    commands:
      # Install required packages
      - apt-get update
      - apt-get install -y curl shellcheck yamllint docker-compose wget

      # Install shfmt
      - wget https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_arm64 -O /usr/local/bin/shfmt
      - chmod +x /usr/local/bin/shfmt
      
      # Format and check shell scripts
      - echo "Formatting shell scripts..."
      - shfmt -l -w -i 4 *.sh
      - echo "Checking shell scripts..."
      - shellcheck *.sh
      
      # Format and check YAML files
      - echo "Checking YAML files..."
      - yamllint -c .yamllint.yml .
      - |
        for file in $(find . -name "*.yml" -o -name "*.yaml"); do
          yamllint -f parsable $file
        done
      
      # Validate docker-compose
      - echo "Validating docker-compose..."
      - docker-compose -f services/docker-compose.yml config
      
      # Security checks
      - echo "Running security checks..."
      - |
        # Check for hardcoded credentials
        ! grep -r -i "password\|secret\|key" --exclude-dir=.git --exclude="*.enc" .
      - |
        # Check for private keys
        ! find . -type f -name "*.pem" -o -name "*.key"

  - name: check-nginx
    image: nginx:alpine
    commands:
      - echo "Validating nginx configuration..."
      - nginx -t -c /etc/nginx/nginx.conf